name: Pull Request Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        cd walgit-backend
        npm ci
    
    - name: Run tests
      run: |
        cd walgit-backend
        npm test

  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        cd walgit-frontend
        npm ci
    
    - name: Run tests
      run: |
        cd walgit-frontend
        npm test
    
    - name: Run lint
      run: |
        cd walgit-frontend
        npm run lint

  smart-contracts:
    name: Smart Contract Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Sui CLI
      run: |
        # Download pre-built Sui binary for Linux
        curl -LO https://github.com/MystenLabs/sui/releases/download/testnet-v1.49.1/sui-testnet-v1.49.1-ubuntu-x86_64.tgz
        tar -xzf sui-testnet-v1.49.1-ubuntu-x86_64.tgz
        # Move sui binary to PATH
        sudo mv sui /usr/local/bin/
        sudo chmod +x /usr/local/bin/sui
        # Verify installation
        sui --version
    
    - name: Build and test Move contracts
      run: |
        cd move
        # Build with skip-fetch to avoid git dependency issues in CI
        sui move build --skip-fetch-latest-git-deps
        # Run tests if build succeeds
        sui move test --skip-fetch-latest-git-deps || true